// src/data/ServicesData.ts
import { FileCheck, Building, Hammer, Home, Users, HeartPulseIcon, Car, Hospital, Accessibility, User, Shield, Lock } from "lucide-react";

export const allServices = [
  {
    id: 1,
    title: 'Barangay Clearance',
    description: 'General clearance used for employment, school, IDs, and business applications.',
    category: 'permits',
    icon: FileCheck,
    processingTime: '1-2 days',
    fee: 'PHP 50',
    popularity: 5,
    availability: 'Business Hours',
    requirements: ['Valid ID', 'Accomplished request form', 'Cedula'],
    featured: true
  },
  {
    id: 2,
    title: 'Barangay Business Permit / Endorsement',
    description: 'Endorsement required before City Hall issues a business permit or for renewal.',
    category: 'business',
    icon: Building,
    processingTime: '2-3 days',
    fee: 'PHP 100',
    popularity: 4,
    availability: 'Business hours',
    requirements: ['Valid ID', 'Business documents'],
    featured: false
  },
  {
    id: 3,
    title: 'Barangay Building/Construction Endorsement',
    description: 'Endorsement certificate for building or construction permits.',
    category: 'permits',
    icon: Hammer,
    processingTime: '2-3 days',
    fee: 'PHP 100',
    popularity: 3,
    availability: 'Business hours',
    requirements: ['Building plan', 'Lot documents', 'Valid ID'],
    featured: false
  },
  {
    id: 4,
    title: 'Certificate of Residency',
    description: 'Proof of residency used for passports, travel, school enrollment, or other government services.',
    category: 'travel',
    icon: Home,
    processingTime: '1 day',
    fee: 'PHP 50',
    popularity: 5,
    availability: 'Business hours',
    requirements: ['Valid ID', 'Proof of Residence'],
    featured: true
  },
  {
    id: 5,
    title: 'Certificate of Indigency',
    description: 'Proof of indigency used for scholarships, medical or hospital assistance, legal aid, or social welfare programs.',
    category: 'social',
    icon: Users,
    processingTime: '1 day',
    fee: 'PHP 50',
    popularity: 5,
    availability: 'Business hours',
    requirements: ['Valid ID', 'Interview with Baranggay Staff'],
    featured: true
  },
  {
    id: 6,
    title: 'Barangay Health Certificate',
    description: 'Issued for food handlers, certain local jobs, or health-related requirements.',
    category: 'health',
    icon: HeartPulseIcon,
    processingTime: '1-2 days',
    fee: 'PHP 100',
    popularity: 4,
    availability: 'Business Hours',
    requirements: ['Medical check-up', 'Valid ID'],
    featured: false
  },
  {
    id: 7,
    title: 'Tricycle Operator’s Permit (TOP) Clearance',
    description: 'Barangay clearance needed before applying for a tricycle franchise.',
    category: 'transport',
    icon: Car,
    processingTime: '2 days',
    fee: 'PHP 150',
    popularity: 2,
    availability: 'Business hours',
    requirements: ['Valid ID', 'Franchise documents'],
    featured: true
  },
  {
    id: 8,
    title: 'Referral Slip to Health Center / Hospital',
    description: 'Barangay referral to access city health services or hospitals.',
    category: 'health',
    icon: Hospital,
    processingTime: 'Same day',
    fee: 'PHP 50',
    popularity: 2,
    availability: 'Business hours',
    requirements: ['Barangay assessment', 'Valid ID'],
    featured: false
  },
  {
    id: 9,
    title: 'Senior Citizen / PWD Certification Endorsement',
    description: 'Endorsement used to apply for senior or PWD IDs and government benefits.',
    category: 'social',
    icon: Accessibility,
    processingTime: '1-2 days',
    fee: 'PHP 50',
    popularity: 4,
    availability: 'Business hours',
    requirements: ['Valid ID', 'Medical proof (if PWD)'],
    featured: true
  },
  {
    id: 10,
    title: 'Solo Parent Certification Endorsement',
    description: 'Endorsement required for Solo Parent ID or benefits application.',
    category: 'social',
    icon: User,
    processingTime: '2 days',
    fee: 'PHP 50',
    popularity: 3,
    availability: 'Business hours',
    requirements: ['Valid ID', 'Proof of solo parent status'],
    featured: false
  },
  {
    id: 11,
    title: 'Barangay Blotter / Certification',
    description: 'Proof of a filed complaint or incident report at the barangay.',
    category: 'security',
    icon: Shield,
    processingTime: 'Same day',
    fee: 'PHP 50',
    popularity: 5,
    availability: '24/7',
    requirements: ['Incident details', 'Valid ID'],
    featured: false
  },
  {
    id: 12,
    title: 'Barangay Protection Order (BPO)',
    description: 'Protection order issued in cases of violence against women and children.',
    category: 'security',
    icon: Lock,
    processingTime: 'Same day',
    fee: 'PHP 0',
    popularity: 5,
    availability: '24/7',
    requirements: ['Complaint details', 'Police report (if available)'],
    featured: false
  }
];
